# # nginx/Dockerfile
# FROM nginx:alpine

# # Copy your custom NGINX config
# COPY nginx.conf /etc/nginx/nginx.conf

# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]



# nginx/Dockerfile
FROM nginx:alpine

# Copy your custom NGINX config
COPY nginx.conf /etc/nginx/nginx.conf

# Copy your built frontend files
COPY ./dist /usr/share/nginx/html


EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
